name: Tag Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd prompt-tools
          npm ci
      - name: Lint (non-blocking)
        working-directory: ./prompt-tools
        run: npm run lint || true
        continue-on-error: true
      - name: Type check
        working-directory: ./prompt-tools
        run: npm run typecheck || true
        continue-on-error: true

  build:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            container: ubuntu:22.04
          - os: windows-2022
          - os: macos-13
            platform: macos
            arch: x64
            targets: x86_64-apple-darwin
          - os: macos-14
            platform: macos
            arch: arm64
            targets: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd prompt-tools
          npm ci

      - name: Install system deps for Linux (Ubuntu 22.04)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          apt-get update && apt-get install -y \
            libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev \
            librsvg2-dev build-essential curl wget file patchelf libssl-dev \
            xdg-utils desktop-file-utils

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets || '' }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            prompt-tools/src-tauri/target
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Tauri app
        run: |
          cd prompt-tools
          npm run tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (filtered bundles only)
        uses: actions/upload-artifact@v4
        with:
          name: prompt-tools-${{ matrix.os }}-${{ matrix.arch || 'unknown' }}
          path: |
            prompt-tools/src-tauri/target/release/bundle/dmg/*.dmg
            prompt-tools/src-tauri/target/release/bundle/macos/*.dmg
            prompt-tools/src-tauri/target/release/bundle/macos/*.app.tar.gz
            prompt-tools/src-tauri/target/release/bundle/appimage/*.AppImage
            prompt-tools/src-tauri/target/release/bundle/deb/*.deb
            prompt-tools/src-tauri/target/release/bundle/rpm/*.rpm
            prompt-tools/src-tauri/target/release/bundle/nsis/*.exe
            prompt-tools/src-tauri/target/release/bundle/msi/*.msi
            prompt-tools/src-tauri/target/release/bundle/**/*.sig
            prompt-tools/src-tauri/target/release/bundle/**/*.sha256*
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Prompt Tools ${{ github.ref_name }}
          files: |
            artifacts/**/*.dmg
            artifacts/**/*.app.tar.gz
            artifacts/**/*.AppImage
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*setup*.exe
            artifacts/**/*.msi
            artifacts/**/*.sig
            artifacts/**/*.sha256*
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}