name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './prompt-tools/src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './prompt-tools/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./prompt-tools
        run: npm ci

      - name: Run Rust tests
        working-directory: ./prompt-tools/src-tauri
        run: cargo test

      - name: Run Rust clippy
        working-directory: ./prompt-tools/src-tauri
        run: cargo clippy -- -D warnings

      - name: Check Rust formatting
        working-directory: ./prompt-tools/src-tauri
        run: cargo fmt --check

      - name: Run frontend linting
        working-directory: ./prompt-tools
        run: npm run lint || true

      - name: Run frontend tests
        working-directory: ./prompt-tools
        run: npm test || true