name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./prompt-tools
        run: npm ci
      - name: Lint (non-blocking)
        working-directory: ./prompt-tools
        run: npm run lint || true
        continue-on-error: true
      - name: Type check
        working-directory: ./prompt-tools
        run: npm run typecheck || true
        continue-on-error: true
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            prompt-tools/src-tauri/target
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run Rust tests
        working-directory: ./prompt-tools/src-tauri
        run: cargo test
      - name: Run Rust clippy
        working-directory: ./prompt-tools/src-tauri
        run: cargo clippy -- -D warnings
        continue-on-error: true
      - name: Check Rust formatting
        working-directory: ./prompt-tools/src-tauri
        run: cargo fmt --check
        continue-on-error: true